version: "3.8"
services:
  react-app:
    container_name: sf-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${REACT_APP_PORT}:3000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
